#!/bin/sh
output=$(xrandr | grep ' connected ' | awk '{print $1}' | head -1)
screenSize=$(xrandr | awk 'BEGIN {foundOutput=0}
    / '$output' / {foundOutput=1}
    /\*\+/ {print $1}
    /^[^ ]/ {if(foundOutput) exit 0}')
if [ "$screenSize" != "" ]; then
    xrandr --output $output --fb $screenSize --off
    play /usr/share/sounds/freedesktop/stereo/monitor-off.oga 2>/dev/null || play /usr/share/sounds/freedesktop/stereo/bell.oga 2>/dev/null || true
else
    xrandr --output $output --auto
    play /usr/share/sounds/freedesktop/stereo/monitor-on.oga 2>/dev/null || play /usr/share/sounds/freedesktop/stereo/bell.oga 2>/dev/null || true
fi

